In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sqlalchemy as sqla
import numpy as np

I want to write some user defined functions

In [2]:
list = ['me', 2, 'dislike', 14]

for item in list:
    print(type(item))

<class 'str'>
<class 'int'>
<class 'str'>
<class 'int'>

In [3]:
def area_triangle(base,height):
    area = 0.5 * base * height
    print(area)

area_triangle(3,6)

9.0

In [6]:
evals = pd.read_csv('../partner_eda/partner_project_evals.csv')
evals

C:\Users\plann\AppData\Local\Temp\ipykernel_35952\2331705836.py:1: DtypeWarning: Columns (0,44) have mixed types. Specify dtype option on import or set low_memory=False.
  evals = pd.read_csv('../partner_eda/partner_project_evals.csv')

,Child ID,Gender,Date of Birth,Location - Sub Level 1,contract number,Program Label,Adaptive Sum of Scaled Scores,Adaptive Developmental Quotient,Adaptive Percentile Rank,Adaptive 95% Confidence Interval,...,Code 1,Code 2,Code 3,Code 4,Code 5,Code 6,Code 7,Code 8,Code 9,Code 10
0,44879,F,9/27/2022,Southwest,contract 3,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47795,F,12/23/2020,Greater Nashville,contract 2,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54340,M,6/22/2021,First Tennessee,contract 1,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,54344,F,3/7/2022,Southeast Tennessee,contract 1,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,54515,M,11/4/2021,Memphis Delta,contract 3,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,SP03287,F,9/25/2023,Memphis Delta,contract 3,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23943,SP03288,F,5/18/2021,South Central,contract 2,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23944,SP03289,F,10/31/2021,South Central,contract 2,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23945,SP03290,M,3/25/2020,Memphis Delta,contract 3,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23946,SP03291,M,9/18/2023,Greater Nashville,contract 2,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
evals.columns

Index(['Child ID', 'Gender', 'Date of Birth', 'Location - Sub Level 1',
       'contract number', 'Program Label', 'Adaptive Sum of Scaled Scores',
       'Adaptive Developmental Quotient', 'Adaptive Percentile Rank',
       'Adaptive 95% Confidence Interval',
       ...
       'Code 1', 'Code 2', 'Code 3', 'Code 4', 'Code 5', 'Code 6', 'Code 7',
       'Code 8', 'Code 9', 'Code 10'],
      dtype='object', length=220)

In [15]:
columns = ['Child ID', 'Gender', 'Date of Birth', 'Location - Sub Level 1',
       'contract number', 'Program Label', 'Adaptive Sum of Scaled Scores',
       'Adaptive Developmental Quotient', 'Adaptive Percentile Rank',
       'Adaptive 95% Confidence Interval']

for column in columns:
    if column.contains('Interval'):
        print('interval')

AttributeError: 'str' object has no attribute 'contains'

In [29]:
starwars_df = pd.read_csv("C:\\Users\\plann\\Documents\\Nashville Software School\\Python\\data\\starwars(1).csv")
starwars_df

,name,height,height order,mass,hair_color,skin_color,eye_color,age,homeworld,species,films
0,Yoda,66,1.0,17.0,white,green,brown,896.0,NaN,Yoda's species,"Attack of the Clones , The Phantom Menace , ..."
1,Ratts Tyerell,79,2.0,15.0,none,"grey, blue",unknown,NaN,Aleen Minor,Aleena,The Phantom Menace
2,Wicket Systri Warrick,88,3.0,20.0,brown,brown,brown,8.0,Endor,Ewok,Return of the Jedi
3,Dud Bolt,94,4.0,45.0,none,"blue, grey",yellow,NaN,Vulpter,Vulptereen,The Phantom Menace
4,R2-D2,96,5.0,32.0,NaN,"white, blue",red,33.0,Naboo,Droid,"Attack of the Clones , The Phantom Menace , ..."
...,...,...,...,...,...,...,...,...,...,...,...
85,BB8,NaN,86.0,NaN,none,none,black,NaN,NaN,Droid,The Force Awakens
86,Captain Phasma,NaN,87.0,NaN,unknown,unknown,unknown,NaN,NaN,NaN,The Force Awakens
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
name_list = starwars_df['name'].to_list()
name_list

['Yoda',
 'Ratts\xa0Tyerell',
 'Wicket\xa0Systri\xa0Warrick',
 'Dud\xa0Bolt',
 'R2-D2',
 'R4-P17',
 'R5-D4',
 'Sebulba',
 'Gasgano',
 'Watto',
 'Leia\xa0Organa',
 'Mon\xa0Mothma',
 'Cordé',
 'Nien\xa0Nunb',
 'Shmi\xa0Skywalker',
 'Ben\xa0Quadinaros',
 'Beru\xa0Whitesun\xa0lars',
 'Dormé',
 'Padmé\xa0Amidala',
 'Barriss\xa0Offee',
 'C-3PO',
 'Jocasta\xa0Nu',
 'Zam\xa0Wesell',
 'Wedge\xa0Antilles',
 'Palpatine',
 'Finis\xa0Valorum',
 'Luminara\xa0Unduli',
 'Eeth\xa0Koth',
 'Luke\xa0Skywalker',
 'Greedo',
 'Jabba\xa0Desilijic\xa0Tiure',
 'Lobot',
 'Darth\xa0Maul',
 'Lando\xa0Calrissian',
 'Owen\xa0Lars',
 'Ayla\xa0Secura',
 'Shaak\xa0Ti',
 'Sly\xa0Moore',
 'Wilhuff\xa0Tarkin',
 'Han\xa0Solo',
 'Jek\xa0Tono\xa0Porkins',
 'Ackbar',
 'Bib\xa0Fortuna',
 'Obi-Wan\xa0Kenobi',
 'Biggs\xa0Darklighter',
 'Boba\xa0Fett',
 'Ric\xa0Olié',
 'Quarsh\xa0Panaka',
 'Cliegg\xa0Lars',
 'Poggle\xa0the\xa0Lesser',
 'Jango\xa0Fett',
 'Adi\xa0Gallia',
 'Gregar\xa0Typho',
 'Anakin\xa0Skywalker',
 'Mace\xa0Windu',
 'Saesee\xa0Tiin',
 'Plo\xa0Koon',
 'Raymus\xa0Antilles',
 'Bossk',
 'Nute\xa0Gunray',
 'Bail\xa0Prestor\xa0Organa',
 'San\xa0Hill',
 'Qui-Gon\xa0Jinn',
 'Dooku',
 'Wat\xa0Tambor',
 'Jar\xa0Jar\xa0Binks',
 'Kit\xa0Fisto',
 'Mas\xa0Amedda',
 'Ki-Adi-Mundi',
 'Dexter\xa0Jettster',
 'IG-88',
 'Darth\xa0Vader',
 'Rugor\xa0Nass',
 'Tion\xa0Medon',
 'Taun\xa0We',
 'Grievous',
 'Roos\xa0Tarpals',
 'Chewbacca',
 'Lama\xa0Su',
 'Tarfful',
 'Yarael\xa0Poof',
 'Arvel\xa0Crynyd',
 'Finn',
 'Rey',
 'Poe\xa0Dameron',
 'BB8',
 'Captain\xa0Phasma',
 nan,
 nan,
 nan]

In [38]:
for name in name_list:
    if 'Skywalker' in name: #is regex needed here?
        print('strong character')

strong character
strong character
strong character

TypeError: argument of type 'float' is not iterable

In [ ]:
x = starwars['variable']